version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Aslanov11*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  webapi:
    build:
      context: ./DMS
      dockerfile: Dockerfile
    container_name: dms-webapi
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
      - redis
